"""remove savings interest rate

Revision ID: 63d20c5f6057
Revises: 69e7c2d7b031
Create Date: 2026-08-19 22:53:08.870805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '63d20c5f6057'
down_revision: Union[str, Sequence[str], None] = '69e7c2d7b031'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savings_profiles', 'interest_rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savings_profiles', sa.Column('interest_rate', mysql.DECIMAL(precision=6, scale=3), nullable=False))
    # ### end Alembic commands ###
