"""add loan installment principal and interest

Revision ID: ca08fa837167
Revises: 63d20c5f6057
Create Date: 2026-08-21 12:04:47.740577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca08fa837167'
down_revision: Union[str, Sequence[str], None] = '63d20c5f6057'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("loan_installments", sa.Column("principal_due",sa.Numeric(precision=15, scale=2),nullable=False,server_default="0.00",),)
    op.add_column("loan_installments",sa.Column("interest_due",sa.Numeric(precision=15, scale=2),nullable=False,server_default="0.00",))

    op.alter_column("loan_installments","principal_due",server_default=None,)
    op.alter_column("loan_installments","interest_due",server_default=None,)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan_installments', 'interest_due')
    op.drop_column('loan_installments', 'principal_due')
    # ### end Alembic commands ###
