"""add performance indexes for large dataset

Revision ID: dd79edea31a4
Revises: 288b9ce2974a
Create Date: 2026-08-26 10:36:30.995194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd79edea31a4'
down_revision: Union[str, Sequence[str], None] = '288b9ce2974a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_transactions_account_time', 'account_transactions', ['account_id', 'transaction_time'], unique=False)
    op.create_index('ix_loan_installments_account_due_date', 'loan_installments', ['account_id', 'due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_loan_installments_account_due_date', table_name='loan_installments')
    op.drop_index('ix_transactions_account_time', table_name='account_transactions')
    # ### end Alembic commands ###
