from enum import Enum

class AccountType(str, Enum):
    SAVINGS = "SAVINGS"
    LOAN = "LOAN"

class AccountStatus(str, Enum):
    ACTIVE = "ACTIVE"   
    FROZEN = "FROZEN"
    CLOSED = "CLOSED"

class AddressType(str, Enum):
    CURRENT = "CURRENT"
    PERMANENT = "PERMANENT"

class TransactionType(str, Enum):
    DEPOSIT = "DEPOSIT"
    WITHDRAWAL = "WITHDRAWAL"
    LOAN_DISBURSEMENT = "LOAN_DISBURSEMENT"
    LOAN_REPAYMENT = "LOAN_REPAYMENT"
    INTEREST_CREDIT = "INTEREST_CREDIT"
    ADJUSTMENT = "ADJUSTMENT"

class InstallmentStatus(str, Enum):
    PENDING = "PENDING"
    PARTIAL = "PARTIAL"
    PAID = "PAID"
    OVERDUE = "OVERDUE"

class AdminStatus(str, Enum):
    ACTIVE = "ACTIVE"
    DISABLED = "DISABLED"
    LOCKED = "LOCKED"

class AuditEventType(str, Enum):
    CUSTOMER_CREATED = "CUSTOMER_CREATED"
    CUSTOMER_UPDATED = "CUSTOMER_UPDATED"

    ADDRESS_ADDED = "ADDRESS_ADDED"
    ADDRESS_UPDATED = "ADDRESS_UPDATED"
    ADDRESS_REMOVED = "ADDRESS_REMOVED"

    ACCOUNT_CREATED = "ACCOUNT_CREATED"
    ACCOUNT_STATUS_CHANGED = "ACCOUNT_STATUS_CHANGED"
    
    LOAN_CREATED = "LOAN_CREATED"
    LOAN_INSTALLMENT_UPDATED = "LOAN_INSTALLMENT_UPDATED"
